"use client";

import { useEffect, useMemo, useState } from "react";
import { BarChart3, CalendarDays, CreditCard, DollarSign, ReceiptText, TrendingUp, Wallet, X } from "lucide-react";
import AppShell from "../components/AppShell";
import { CashClosure, KEYS, Sale, load, money } from "../lib/storage";

const meses=["Enero","Febrero","Marzo","Abril","Mayo","Junio","Julio","Agosto","Septiembre","Octubre","Noviembre","Diciembre"];
const weekDays=["Lun","Mar","Mié","Jue","Vie","Sáb","Dom"];
const REPORT_YEARS=[2026,2027];

export default function ReportesPage(){
 const[sales,setSales]=useState<Sale[]>([]),[closures,setClosures]=useState<CashClosure[]>([]);
 const[selectedYear,setSelectedYear]=useState(2026),[selectedMonth,setSelectedMonth]=useState(0),[selectedDay,setSelectedDay]=useState<number|null>(null);
 const[yearModal,setYearModal]=useState(false),[monthModal,setMonthModal]=useState(false),[dayModal,setDayModal]=useState(false);
 useEffect(()=>{setSales(load<Sale[]>(KEYS.sales,[]));setClosures(load<CashClosure[]>(KEYS.cashClosures,[]))},[]);
 const valores=useMemo(()=>meses.map((mes,index)=>{const ms=sales.filter(s=>{const d=new Date(s.createdAt);return d.getFullYear()===selectedYear&&d.getMonth()===index});return{mes,total:ms.reduce((a,s)=>a+s.total,0),cantidad:ms.length}}),[sales,selectedYear]);
 const max=Math.max(...valores.map(v=>v.total),1),totalAnual=valores.reduce((a,v)=>a+v.total,0),promedio=totalAnual/12,activeMonths=valores.filter(v=>v.cantidad>0).length;
 const totalTarjeta=useMemo(()=>sales.filter(s=>new Date(s.createdAt).getFullYear()===selectedYear).reduce((sum,s)=>{if(s.method==="Débito"||s.method==="Crédito")return sum+s.total;if(s.method==="Pago mixto"&&(s.secondaryMethod==="Débito"||s.secondaryMethod==="Crédito"))return sum+(Number(s.otherAmount)||0);return sum},0),[sales,selectedYear]);
 const currentMonth=new Date().getFullYear()===selectedYear?new Date().getMonth():0;
 const previousMonth=currentMonth===0?0:currentMonth-1;
 const miniMonths=[previousMonth,currentMonth].filter((v,i,a)=>a.indexOf(v)===i);
 const miniMax=Math.max(...miniMonths.map(i=>valores[i].total),1);
 const latestClosure=useMemo(()=>closures.filter(c=>c.year===selectedYear).sort((a,b)=>new Date(b.closedAt).getTime()-new Date(a.closedAt).getTime())[0],[closures,selectedYear]);
 const selectedMonthSales=useMemo(()=>sales.filter(s=>{const d=new Date(s.createdAt);return d.getFullYear()===selectedYear&&d.getMonth()===selectedMonth}),[sales,selectedYear,selectedMonth]);
 const daysInMonth=new Date(selectedYear,selectedMonth+1,0).getDate(),firstWeekday=(new Date(selectedYear,selectedMonth,1).getDay()+6)%7;
 const selectedDaySales=useMemo(()=>selectedDay===null?[]:selectedMonthSales.filter(s=>new Date(s.createdAt).getDate()===selectedDay),[selectedDay,selectedMonthSales]);
 const selectedDayTotal=selectedDaySales.reduce((a,s)=>a+s.total,0),selectedDayNet=selectedDaySales.reduce((a,s)=>a+(typeof s.netTotal==="number"?s.netTotal:s.total-(s.commission||0)),0);
 const selectedClosure=closures.find(c=>c.year===selectedYear&&c.month===meses[selectedMonth]);
 function changeYear(y:number){setSelectedYear(y);setSelectedMonth(0);setSelectedDay(null);setYearModal(false);setMonthModal(false);setDayModal(false)}
 function openMonth(i:number){setSelectedMonth(i);setSelectedDay(null);setMonthModal(true);setDayModal(false)}
 function openDay(d:number){setSelectedDay(d);setDayModal(true)}
 const yearSelector=<div style={{display:"inline-flex",gap:6,padding:4,border:"1px solid var(--border)",borderRadius:12,background:"#fff"}}>{REPORT_YEARS.map(y=><button key={y} type="button" onClick={()=>changeYear(y)} style={{border:0,borderRadius:9,padding:"7px 12px",fontWeight:900,cursor:"pointer",background:selectedYear===y?"var(--green-soft)":"transparent",color:selectedYear===y?"var(--green-dark)":"var(--muted)"}}>{y}</button>)}</div>;
 return <AppShell title={`Meses y reportes · ${selectedYear}`} subtitle="Resumen anual, meses y detalle diario de ventas." active="Meses y reportes" action={yearSelector}>
  <section className="kpis page-kpis"><div className="card kpi-card"><div className="kpi-top"><span className="icon-box"><DollarSign size={19}/></span></div><div className="kpi-label">Ventas de {selectedYear}</div><div className="kpi-value">{money.format(totalAnual)}</div><div className="kpi-foot">Total acumulado</div></div><div className="card kpi-card"><div className="kpi-top"><span className="icon-box"><TrendingUp size={19}/></span></div><div className="kpi-label">Promedio mensual</div><div className="kpi-value">{money.format(promedio)}</div><div className="kpi-foot">Promedio sobre 12 meses</div></div><div className="card kpi-card"><div className="kpi-top"><span className="icon-box"><CalendarDays size={19}/></span></div><div className="kpi-label">Meses con ventas</div><div className="kpi-value">{activeMonths}</div><div className="kpi-foot">De 12 meses</div></div><div className="card kpi-card"><div className="kpi-top"><span className="icon-box"><CreditCard size={19}/></span></div><div className="kpi-label">Total en tarjeta</div><div className="kpi-value">{money.format(totalTarjeta)}</div><div className="kpi-foot">Bruto · sin descontar comisión bancaria</div></div></section>

  <section className="section-gap" style={{display:"grid",gridTemplateColumns:"minmax(320px,520px) minmax(320px,1fr)",gap:16,alignItems:"stretch"}}>
   <section className="card" style={{padding:16}} onClick={()=>setYearModal(true)}>
    <div className="card-heading"><div><h2 style={{fontSize:15}}>Comparativa mensual</h2><p>Vista mínima · haz clic para ver todo {selectedYear}.</p></div><span className="warning-circle" style={{background:"var(--green-soft)",color:"var(--green-dark)"}}><BarChart3 size={16}/></span></div>
    <button type="button" onClick={()=>setYearModal(true)} style={{width:"100%",border:0,background:"transparent",cursor:"pointer",padding:0,marginTop:10}}><div style={{height:118,display:"flex",alignItems:"flex-end",justifyContent:"center",gap:34,borderBottom:"1px solid var(--border)",padding:"4px 20px 22px"}}>{miniMonths.map(i=>{const h=valores[i].total===0?4:Math.max(10,(valores[i].total/miniMax)*72);return <div key={i} style={{width:90,display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"flex-end",height:"100%",gap:5}}><small style={{fontSize:9,fontWeight:900}}>{money.format(valores[i].total)}</small><div style={{width:34,height:h,borderRadius:"7px 7px 2px 2px",background:i===currentMonth?"var(--green-dark)":"#9bb9a4"}}/><span style={{fontSize:9,fontWeight:900,color:"var(--muted)"}}>{meses[i].slice(0,3)}</span></div>})}</div></button>
   </section>

   <section className="card" style={{padding:16}}>
    <div className="card-heading"><div><h2 style={{fontSize:15}}>Cierre de mes</h2><p>Se completa cuando confirmas el cierre desde Caja.</p></div><span className="warning-circle" style={{background:"var(--green-soft)",color:"var(--green-dark)"}}><Wallet size={16}/></span></div>
    {!latestClosure?<div className="empty-state compact" style={{minHeight:118,marginTop:10}}><ReceiptText size={28}/><b>Sin cierre registrado</b><span>Cuando cierres un mes en Caja, aparecerá aquí.</span></div>:<><div style={{marginTop:10,fontSize:10,fontWeight:900,color:"var(--green-dark)"}}>{latestClosure.month} {latestClosure.year}</div><div style={{display:"grid",gridTemplateColumns:"repeat(3,minmax(0,1fr))",gap:9,marginTop:10}}><div style={miniCard}><small>Venta neta</small><b>{typeof latestClosure.netSales==="number"?money.format(latestClosure.netSales):"—"}</b></div><div style={miniCard}><small>Gastos</small><b>{money.format(latestClosure.expenses)}</b></div><div style={miniCard}><small>Efectivo</small><b>{typeof latestClosure.cashOnHand==="number"?money.format(latestClosure.cashOnHand):"—"}</b></div></div><div style={{marginTop:9,fontSize:9,color:"var(--muted)"}}>Cerrado el {new Date(latestClosure.closedAt).toLocaleDateString("es-AR")}</div></>}
   </section>
  </section>

  <section className="card section-gap"><div className="card-heading"><div><h2>Todo el año {selectedYear}</h2><p>Haz clic en un mes para abrir su calendario.</p></div></div><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(170px,1fr))",gap:12,marginTop:18}}>{valores.map((item,index)=><button type="button" key={item.mes} onClick={()=>openMonth(index)} style={{textAlign:"left",border:"1px solid var(--border)",borderRadius:14,padding:14,background:"#fff",cursor:"pointer"}}><div style={{display:"flex",justifyContent:"space-between",gap:8}}><b style={{fontSize:11,color:"var(--muted)"}}>{item.mes}</b><span style={{fontSize:9,fontWeight:900,color:"var(--green-dark)"}}>{String(index+1).padStart(2,"0")}/{selectedYear}</span></div><div style={{marginTop:5,fontSize:20,fontWeight:900}}>{money.format(item.total)}</div><div style={{marginTop:4,fontSize:9,color:"#8b958f"}}>{item.cantidad?`${item.cantidad} venta(s)`:"Sin ventas registradas"}</div></button>)}</div></section>

  {yearModal&&<div role="dialog" aria-modal="true" style={overlay} onMouseDown={e=>{if(e.target===e.currentTarget)setYearModal(false)}}><div style={modal}><div style={modalHead}><div><small style={eyebrow}>{selectedYear}</small><h2 style={{margin:"3px 0"}}>Comparativa de todo el año</h2><p style={muted}>Facturación de enero a diciembre.</p></div><button className="ghost-button" onClick={()=>setYearModal(false)}><X size={18}/></button></div><div style={{overflowX:"auto",marginTop:18}}><div style={{minWidth:700,height:280,display:"flex",alignItems:"flex-end",gap:12,borderBottom:"1px solid var(--border)",padding:"10px 4px 28px"}}>{valores.map((v,i)=>{const h=v.total===0?4:Math.max(10,(v.total/max)*205);return <div key={v.mes} style={{flex:1,minWidth:42,height:"100%",display:"flex",flexDirection:"column",justifyContent:"flex-end",alignItems:"center",gap:7}}><small style={{fontSize:9,fontWeight:800}}>{money.format(v.total)}</small><div style={{width:"65%",maxWidth:38,height:h,borderRadius:"8px 8px 2px 2px",background:"var(--green-dark)"}}/><b style={{fontSize:9,color:"var(--muted)"}}>{v.mes.slice(0,3)}</b></div>})}</div></div></div></div>}

  {monthModal&&<div role="dialog" aria-modal="true" style={overlay} onMouseDown={e=>{if(e.target===e.currentTarget)setMonthModal(false)}}><div style={{...modal,width:"min(820px,96vw)"}}><div style={modalHead}><div><small style={eyebrow}>{selectedYear}</small><h2 style={{margin:"3px 0"}}>{meses[selectedMonth]}</h2><p style={muted}>Selecciona un día para ver sus ventas.</p></div><button className="ghost-button" onClick={()=>setMonthModal(false)}><X size={18}/></button></div><div style={{display:"grid",gridTemplateColumns:"repeat(7,minmax(58px,1fr))",gap:7,marginTop:18,overflowX:"auto"}}>{weekDays.map(d=><div key={d} style={{fontSize:9,fontWeight:900,textAlign:"center",color:"var(--muted)",padding:5}}>{d}</div>)}{Array.from({length:firstWeekday}).map((_,i)=><div key={`e${i}`}/>)}{Array.from({length:daysInMonth},(_,i)=>i+1).map(day=>{const ds=selectedMonthSales.filter(s=>new Date(s.createdAt).getDate()===day),total=ds.reduce((a,s)=>a+s.total,0);return <button key={day} type="button" onClick={()=>openDay(day)} style={{minHeight:74,border:"1px solid var(--border)",borderRadius:11,background:ds.length?"var(--green-soft)":"#fff",padding:8,textAlign:"left",cursor:"pointer"}}><b>{day}</b><div style={{fontSize:8,color:"var(--muted)",marginTop:7}}>{ds.length?`${ds.length} venta(s)`:"Sin ventas"}</div>{ds.length>0&&<div style={{fontSize:9,fontWeight:900,color:"var(--green-dark)",marginTop:2}}>{money.format(total)}</div>}</button>})}</div><div style={{marginTop:18,paddingTop:14,borderTop:"1px solid var(--border)"}}><div style={{display:"flex",alignItems:"center",gap:8}}><ReceiptText size={17}/><b style={{fontSize:12}}>Cierre de mes</b></div>{!selectedClosure?<p style={muted}>Mes todavía abierto.</p>:<div style={{display:"flex",gap:18,flexWrap:"wrap",marginTop:8,fontSize:11}}><span>Venta neta <b>{typeof selectedClosure.netSales==="number"?money.format(selectedClosure.netSales):"—"}</b></span><span>Gastos <b>{money.format(selectedClosure.expenses)}</b></span><span>Efectivo <b>{typeof selectedClosure.cashOnHand==="number"?money.format(selectedClosure.cashOnHand):"—"}</b></span></div>}</div></div></div>}

  {dayModal&&selectedDay!==null&&<div role="dialog" aria-modal="true" style={{...overlay,zIndex:1100}} onMouseDown={e=>{if(e.target===e.currentTarget)setDayModal(false)}}><div style={{...modal,width:"min(760px,94vw)"}}><div style={modalHead}><div><small style={eyebrow}>{selectedDay} de {meses[selectedMonth]} · {selectedYear}</small><h2 style={{margin:"3px 0"}}>Detalle de ventas</h2><p style={muted}>{selectedDaySales.length?`${selectedDaySales.length} operación(es)`:"No hubo ventas este día"}</p></div><button className="ghost-button" onClick={()=>setDayModal(false)}><X size={18}/></button></div>{selectedDaySales.length===0?<div className="empty-state compact" style={{marginTop:18}}><CalendarDays size={28}/><b>Sin ventas registradas</b></div>:<><div style={{display:"grid",gridTemplateColumns:"repeat(3,minmax(0,1fr))",gap:9,marginTop:15}}><div style={miniCard}><small>Venta bruta</small><b>{money.format(selectedDayTotal)}</b></div><div style={miniCard}><small>Venta neta</small><b>{money.format(selectedDayNet)}</b></div><div style={miniCard}><small>Operaciones</small><b>{selectedDaySales.length}</b></div></div><div style={{display:"grid",gap:9,marginTop:14,maxHeight:430,overflowY:"auto"}}>{selectedDaySales.map(s=><article key={s.id} style={{border:"1px solid var(--border)",borderRadius:13,padding:12}}><div style={{display:"flex",justifyContent:"space-between",gap:10}}><div><b style={{fontSize:11}}>Venta #{String(s.id).slice(-6)}</b><small style={{display:"block",color:"var(--muted)",marginTop:2}}>{new Date(s.createdAt).toLocaleTimeString("es-AR",{hour:"2-digit",minute:"2-digit"})}</small></div><strong>{money.format(s.total)}</strong></div><div style={{marginTop:9,fontSize:10,fontWeight:800}}>{s.items.map(i=>`${i.qty}× ${i.name} · ${money.format(i.price)}`).join("  |  ")}</div><div style={{display:"flex",gap:12,flexWrap:"wrap",marginTop:9,fontSize:9,color:"var(--muted)"}}><span>Pago: <b>{s.method}</b></span>{s.secondaryMethod&&<span>+ <b>{s.secondaryMethod}</b></span>}{s.provider&&<span>Banco: <b>{s.provider}</b></span>}{typeof s.commission==="number"&&s.commission>0&&<span>Comisión: <b>{money.format(s.commission)}</b></span>}<span>Neto: <b>{money.format(typeof s.netTotal==="number"?s.netTotal:s.total-(s.commission||0))}</b></span></div></article>)}</div></>}</div></div>}
 </AppShell>;
}

const overlay:React.CSSProperties={position:"fixed",inset:0,zIndex:1000,background:"rgba(18,27,22,.42)",display:"flex",alignItems:"center",justifyContent:"center",padding:18};
const modal:React.CSSProperties={width:"min(900px,96vw)",maxHeight:"88vh",overflowY:"auto",background:"#fff",borderRadius:20,border:"1px solid var(--border)",boxShadow:"0 24px 70px rgba(0,0,0,.18)",padding:20};
const modalHead:React.CSSProperties={display:"flex",justifyContent:"space-between",alignItems:"flex-start",gap:14,borderBottom:"1px solid var(--border)",paddingBottom:12};
const eyebrow:React.CSSProperties={fontWeight:900,color:"var(--green-dark)",fontSize:10};
const muted:React.CSSProperties={margin:"4px 0 0",color:"var(--muted)",fontSize:10};
const miniCard:React.CSSProperties={border:"1px solid var(--border)",borderRadius:12,padding:11,display:"grid",gap:4,fontSize:10};
