"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { ArrowLeftRight, Banknote, CalendarDays, CheckCircle2, Landmark, Plus, ReceiptText, Trash2, Wallet, X } from "lucide-react";
import AppShell from "../components/AppShell";
import { CashClosure, CashMovement, KEYS, Sale, load, money, save } from "../lib/storage";

const expenseCategories = ["Alquiler", "Mercadería", "Servicios", "Comisiones", "Insumos", "Impuestos", "Otros"];
const monthNames = ["Enero","Febrero","Marzo","Abril","Mayo","Junio","Julio","Agosto","Septiembre","Octubre","Noviembre","Diciembre"];
const exchangeMethods = ["Efectivo","Cuenta bancaria"];
const bankMethods = new Set(["Cuenta bancaria","Transferencia","Débito","Crédito","QR","PIX"]);
const localDateValue=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`};
const dateToIso=(date:string)=>{const today=localDateValue();if(date===today)return new Date().toISOString();const [y,m,d]=date.split("-").map(Number);return new Date(y,m-1,d,12,0,0).toISOString()};

export default function CajaPage() {
  const [open, setOpen] = useState(false), [showExchange,setShowExchange]=useState(false), [showClose,setShowClose]=useState(false);
  const [movements,setMovements]=useState<CashMovement[]>([]), [sales,setSales]=useState<Sale[]>([]), [closures,setClosures]=useState<CashClosure[]>([]), [hydrated,setHydrated]=useState(false);
  const [type,setType]=useState<"Ingreso"|"Egreso">("Ingreso"), [concept,setConcept]=useState(""), [amount,setAmount]=useState(""), [method,setMethod]=useState("Efectivo"), [note,setNote]=useState(""), [category,setCategory]=useState("Otros"), [movementDate,setMovementDate]=useState(localDateValue());
  const [exchangeFrom,setExchangeFrom]=useState("Efectivo"), [exchangeTo,setExchangeTo]=useState("Cuenta bancaria"), [exchangeAmount,setExchangeAmount]=useState(""), [exchangeNote,setExchangeNote]=useState(""), [exchangeDate,setExchangeDate]=useState(localDateValue());
  const [period,setPeriod]=useState("Hoy"); const now=new Date(); const [reportMonth,setReportMonth]=useState(now.getMonth()), [reportYear,setReportYear]=useState(now.getFullYear());

  useEffect(()=>{setMovements(load<CashMovement[]>(KEYS.cash,[]));setSales(load<Sale[]>(KEYS.sales,[]));setClosures(load<CashClosure[]>(KEYS.cashClosures,[]));setHydrated(true)},[]);
  useEffect(()=>{if(hydrated)save(KEYS.cash,movements)},[movements,hydrated]); useEffect(()=>{if(hydrated)save(KEYS.cashClosures,closures)},[closures,hydrated]);

  const cashBalance=useMemo(()=>movements.filter(m=>m.method==="Efectivo").reduce((s,m)=>s+(m.type==="Ingreso"?m.amount:-m.amount),0),[movements]);
  const bankMovementBalance=useMemo(()=>movements.filter(m=>bankMethods.has(m.method)).reduce((s,m)=>s+(m.type==="Ingreso"?m.amount:-m.amount),0),[movements]);
  const bankSalesBalance=useMemo(()=>sales.filter(s=>s.method!=="Efectivo"&&s.deposited===true).reduce((sum,s)=>{const commission=s.commission||0;if(s.method==="Pago mixto")return sum+Math.max(0,(s.otherAmount||0)-commission);return sum+(typeof s.netTotal==="number"?s.netTotal:Math.max(0,s.total-commission))},0),[sales]);
  const bankBalance=bankMovementBalance+bankSalesBalance;
  const totalAvailable=cashBalance+bankBalance;
  const operatingMovements=useMemo(()=>movements.filter(m=>m.source!=="exchange"),[movements]);
  const filtered=useMemo(()=>{const current=new Date();return movements.filter(m=>{const d=new Date(m.createdAt);if(period==="Hoy")return d.toDateString()===current.toDateString();if(period==="Esta semana")return current.getTime()-d.getTime()<=7*86400000;return d.getMonth()===current.getMonth()&&d.getFullYear()===current.getFullYear()})},[movements,period]);
  const monthlyMovements=useMemo(()=>movements.filter(m=>{const d=new Date(m.createdAt);return d.getMonth()===reportMonth&&d.getFullYear()===reportYear}),[movements,reportMonth,reportYear]);
  const monthlyOperating=useMemo(()=>monthlyMovements.filter(m=>m.source!=="exchange"),[monthlyMovements]);
  const monthlySales=useMemo(()=>sales.filter(s=>{const d=new Date(s.createdAt);return d.getMonth()===reportMonth&&d.getFullYear()===reportYear}),[sales,reportMonth,reportYear]);
  const monthlyReport=useMemo(()=>{const income=monthlyOperating.filter(m=>m.type==="Ingreso").reduce((s,m)=>s+m.amount,0),expenses=monthlyOperating.filter(m=>m.type==="Egreso").reduce((s,m)=>s+m.amount,0),netSales=monthlySales.reduce((s,v)=>s+(typeof v.netTotal==="number"?v.netTotal:v.total-(v.commission||0)),0),cashIncome=monthlyMovements.filter(m=>m.type==="Ingreso"&&m.method==="Efectivo").reduce((s,m)=>s+m.amount,0),cashExpenses=monthlyMovements.filter(m=>m.type==="Egreso"&&m.method==="Efectivo").reduce((s,m)=>s+m.amount,0),breakdown:Record<string,number>={};monthlyOperating.filter(m=>m.type==="Egreso").forEach(m=>{const k=m.category||"Otros";breakdown[k]=(breakdown[k]||0)+m.amount});return{income,expenses,balance:income-expenses,netSales,cashOnHand:cashIncome-cashExpenses,breakdown}},[monthlyMovements,monthlyOperating,monthlySales]);
  const existingClosure=closures.find(c=>c.month===monthNames[reportMonth]&&c.year===reportYear);

  function resetForm(){setType("Ingreso");setConcept("");setAmount("");setMethod("Efectivo");setNote("");setCategory("Otros");setMovementDate(localDateValue())}
  function saveMovement(e:FormEvent){e.preventDefault();const n=Number(amount.replace(",","."));if(!concept.trim()||!Number.isFinite(n)||n<=0||!movementDate)return;setMovements(v=>[{id:Date.now(),type,concept:concept.trim(),amount:n,method,note:note.trim(),createdAt:dateToIso(movementDate),source:"manual",category:type==="Egreso"?category:undefined},...v]);resetForm();setOpen(false)}
  function saveExchange(e:FormEvent){e.preventDefault();const n=Number(exchangeAmount.replace(",","."));if(!Number.isFinite(n)||n<=0||exchangeFrom===exchangeTo||!exchangeDate)return;const id=Date.now(),createdAt=dateToIso(exchangeDate),concept=`Cambio de dinero · ${exchangeFrom} → ${exchangeTo}`,note=exchangeNote.trim()||"Cambio de dinero";setMovements(v=>[{id:id+1,type:"Ingreso",concept,amount:n,method:exchangeTo,note,createdAt,source:"exchange"},{id,type:"Egreso",concept,amount:n,method:exchangeFrom,note,createdAt,source:"exchange"},...v]);setExchangeAmount("");setExchangeNote("");setExchangeDate(localDateValue());setShowExchange(false)}
  function removeMovement(id:number){const target=movements.find(m=>m.id===id);if(target?.source==="exchange"){setMovements(v=>v.filter(m=>!(m.source==="exchange"&&m.createdAt===target.createdAt)));return}setMovements(v=>v.filter(m=>m.id!==id))}
  function closeMonth(){if(existingClosure)return;setClosures(v=>[{id:Date.now(),month:monthNames[reportMonth],year:reportYear,income:monthlyReport.income,expenses:monthlyReport.expenses,balance:monthlyReport.balance,netSales:monthlyReport.netSales,cashOnHand:monthlyReport.cashOnHand,movementCount:monthlyMovements.length,expenseBreakdown:monthlyReport.breakdown,closedAt:new Date().toISOString()},...v]);setShowClose(false)}

  return <AppShell title="Caja" subtitle="Controla el efectivo, la cuenta bancaria y los movimientos del negocio." active="Caja" titleAction={<button className="outline-action" onClick={()=>setShowClose(true)}><CheckCircle2 size={17}/> Cerrar mes</button>}>
    <section className="kpis page-kpis"><div className="card kpi-card"><div className="kpi-top"><span className="icon-box"><Banknote size={19}/></span></div><div className="kpi-label">Efectivo en caja</div><div className="kpi-value">{money.format(cashBalance)}</div><div className="kpi-foot">Lo que debería haber físicamente en el local</div></div><div className="card kpi-card"><div className="kpi-top"><span className="icon-box"><Landmark size={19}/></span></div><div className="kpi-label">Cuenta bancaria</div><div className="kpi-value">{money.format(bankBalance)}</div><div className="kpi-foot">Ventas acreditadas y movimientos bancarios</div></div><div className="card kpi-card"><div className="kpi-top"><span className="icon-box"><Wallet size={19}/></span></div><div className="kpi-label">Total disponible</div><div className="kpi-value">{money.format(totalAvailable)}</div><div className="kpi-foot">Efectivo + cuenta bancaria</div></div></section>

    {open&&<section className="card workspace-card section-gap"><div className="card-heading"><div><h2>Nuevo movimiento</h2><p>Registra un ingreso o egreso manual en el lugar donde realmente entra o sale el dinero.</p></div><button className="ghost-button" onClick={()=>setOpen(false)}><X size={17}/> Cerrar</button></div><form className="form-grid" onSubmit={saveMovement}><label className="field-label">Fecha<input type="date" value={movementDate} max={localDateValue()} onChange={e=>setMovementDate(e.target.value)} required/></label><label className="field-label">Tipo<select value={type} onChange={e=>setType(e.target.value as "Ingreso"|"Egreso")}><option>Ingreso</option><option>Egreso</option></select></label><label className="field-label">Concepto<input value={concept} onChange={e=>setConcept(e.target.value)} required/></label><label className="field-label">Monto<input value={amount} onChange={e=>setAmount(e.target.value)} inputMode="decimal" required/></label><label className="field-label">Dónde se mueve el dinero<select value={method} onChange={e=>setMethod(e.target.value)}><option>Efectivo</option><option>Cuenta bancaria</option></select></label>{type==="Egreso"&&<label className="field-label">Categoría de gasto<select value={category} onChange={e=>setCategory(e.target.value)}>{expenseCategories.map(c=><option key={c}>{c}</option>)}</select></label>}<label className="field-label" style={{gridColumn:"1 / -1"}}>Observación <small>Opcional</small><input value={note} onChange={e=>setNote(e.target.value)}/></label><button className="primary-button" type="submit">Guardar movimiento</button></form></section>}

    {showExchange&&<section className="card workspace-card section-gap"><div className="card-heading"><div><h2>Cambio de dinero</h2><p>Mueve dinero entre efectivo y cuenta bancaria sin registrarlo como venta, ingreso o gasto.</p></div><button className="ghost-button" onClick={()=>setShowExchange(false)}><X size={17}/> Cerrar</button></div><form className="form-grid" onSubmit={saveExchange}><label className="field-label">Fecha<input type="date" value={exchangeDate} max={localDateValue()} onChange={e=>setExchangeDate(e.target.value)} required/></label><label className="field-label">Desde<select value={exchangeFrom} onChange={e=>setExchangeFrom(e.target.value)}>{exchangeMethods.map(x=><option key={x}>{x}</option>)}</select></label><label className="field-label">Hacia<select value={exchangeTo} onChange={e=>setExchangeTo(e.target.value)}>{exchangeMethods.map(x=><option key={x}>{x}</option>)}</select></label><label className="field-label">Monto<input value={exchangeAmount} onChange={e=>setExchangeAmount(e.target.value)} inputMode="decimal" required/></label><label className="field-label">Observación <small>Opcional</small><input value={exchangeNote} onChange={e=>setExchangeNote(e.target.value)}/></label><div style={{gridColumn:"1 / -1",padding:12,border:"1px solid var(--border)",borderRadius:12,background:"var(--green-soft)",fontSize:11,fontWeight:800}}>El efectivo baja y la cuenta bancaria sube, o al revés. El total disponible no cambia.</div><button className="primary-button" disabled={exchangeFrom===exchangeTo}><ArrowLeftRight size={16}/> Registrar cambio</button></form></section>}

    <section className="card workspace-card section-gap"><div className="card-heading"><div><h2>Movimientos de caja</h2><p>Ingresos, egresos y cambios internos registrados.</p></div><div style={{display:"flex",gap:8,alignItems:"center",flexWrap:"wrap"}}><button className="primary-button" onClick={()=>{setShowExchange(false);setOpen(true)}}><Plus size={18}/> Nuevo movimiento</button><button className="outline-action" onClick={()=>{setOpen(false);setShowExchange(true)}}><ArrowLeftRight size={17}/> Cambio de dinero</button><select className="period-select" value={period} onChange={e=>setPeriod(e.target.value)}><option>Hoy</option><option>Esta semana</option><option>Este mes</option></select></div></div>{!hydrated?<div className="empty-state"><b>Cargando movimientos...</b></div>:filtered.length===0?<div className="empty-state"><Wallet size={34}/><b>Todavía no hay movimientos</b></div>:<div className="sales-table"><div className="table-head"><span>Fecha</span><span>Concepto</span><span>Tipo</span><span>Cuenta</span><span>Monto</span></div>{filtered.map(m=>{const movementColor=m.source==="exchange"?undefined:(m.type==="Ingreso"?"#16803c":"#c62828");return <div className="table-row" key={m.id}><div><b>{new Date(m.createdAt).toLocaleDateString("es-AR")}</b><small>{new Date(m.createdAt).toLocaleTimeString("es-AR",{hour:"2-digit",minute:"2-digit"})} · {m.note||"Sin observación"}</small></div><span>{m.concept}{m.type==="Egreso"&&m.category?<small style={{display:"block"}}>{m.category}</small>:null}</span><span className="method" style={{color:movementColor,fontWeight:900}}>{m.source==="exchange"?"Cambio":m.type}</span><span>{m.method}</span><strong style={{color:movementColor}}>{m.type==="Egreso"?"-":"+"}{money.format(m.amount)}</strong>{m.source!=="sale"&&<button className="ghost-button" onClick={()=>removeMovement(m.id)}><Trash2 size={14}/></button>}</div>})}</div>}</section>

    {closures.length>0&&<section className="card workspace-card section-gap"><div className="card-heading"><div><h2>Historial de cierres</h2><p>Los reportes cerrados también aparecen automáticamente en Meses y reportes.</p></div><CalendarDays size={20}/></div><div className="sales-table">{closures.map(c=><div className="table-row" key={c.id}><div><b>{c.month} {c.year}</b><small>Cerrado {new Date(c.closedAt).toLocaleDateString("es-AR")}</small></div><span>Venta neta {money.format(c.netSales??0)}</span><span>Gastos {money.format(c.expenses)}</span><span>Efectivo {money.format(c.cashOnHand??0)}</span><strong>{money.format(c.balance)}</strong></div>)}</div></section>}

    {showClose&&<div style={{position:"fixed",inset:0,zIndex:80,background:"rgba(10,18,13,.42)",display:"grid",placeItems:"center",padding:18}} onClick={()=>setShowClose(false)}><section className="card workspace-card" style={{width:"min(820px,100%)",maxHeight:"90vh",overflowY:"auto",boxShadow:"0 24px 80px rgba(0,0,0,.25)"}} onClick={e=>e.stopPropagation()}><div className="card-heading"><div><h2>Reporte mensual de caja</h2><p>Este reporte se genera únicamente al cerrar el mes y quedará guardado en Meses y reportes.</p></div><button className="ghost-button" onClick={()=>setShowClose(false)}><X size={17}/> Cerrar</button></div><div style={{display:"flex",gap:8,flexWrap:"wrap",marginTop:14}}><select className="period-select" value={reportMonth} onChange={e=>setReportMonth(Number(e.target.value))}>{monthNames.map((m,i)=><option key={m} value={i}>{m}</option>)}</select><select className="period-select" value={reportYear} onChange={e=>setReportYear(Number(e.target.value))}>{[now.getFullYear()-1,now.getFullYear(),now.getFullYear()+1].map(y=><option key={y}>{y}</option>)}</select></div><section className="kpis page-kpis" style={{marginTop:14}}><div className="card kpi-card"><div className="kpi-label">Venta neta</div><div className="kpi-value">{money.format(monthlyReport.netSales)}</div></div><div className="card kpi-card"><div className="kpi-label">Gastos del mes</div><div className="kpi-value">{money.format(monthlyReport.expenses)}</div></div><div className="card kpi-card"><div className="kpi-label">Efectivo</div><div className="kpi-value">{money.format(monthlyReport.cashOnHand)}</div></div></section><div className="card-heading" style={{marginTop:18}}><div><h2>Gastos por categoría</h2><p>Detalle incluido en el cierre mensual.</p></div><ReceiptText size={20}/></div>{Object.keys(monthlyReport.breakdown).length===0?<div className="empty-state compact"><ReceiptText size={30}/><b>Sin gastos registrados</b></div>:<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))",gap:10,marginTop:12}}>{Object.entries(monthlyReport.breakdown).sort((a,b)=>b[1]-a[1]).map(([name,total])=><div key={name} style={{border:"1px solid var(--border)",borderRadius:14,padding:14,background:"#fff"}}><small>{name}</small><div style={{fontSize:20,fontWeight:900,marginTop:5}}>{money.format(total)}</div></div>)}</div>}<div style={{marginTop:14,fontSize:11,color:"var(--muted)"}}>{monthlyMovements.length} movimientos incluidos en este cierre.</div>{existingClosure?<div style={{marginTop:16,padding:"12px 14px",border:"1px solid var(--border)",borderRadius:14,background:"var(--green-soft)"}}><b>Este mes ya fue cerrado</b></div>:<button className="primary-button full-button" style={{marginTop:16}} onClick={closeMonth}><CheckCircle2 size={17}/> Confirmar cierre mensual</button>}</section></div>}
  </AppShell>;
}
